In [1]:
import torch
x = torch.tensor([1, 2, 3])
print(x)
print(x.dtype)

tensor([1, 2, 3])
torch.int64


In [2]:
x_float = torch.tensor([1, 2, 3], dtype=torch.float32)
print(x_float)
print(x_float.dtype)

tensor([1., 2., 3.])
torch.float32


In [3]:
x_float.shape

torch.Size([3])

torch.Size([3]) → 1D, 3 eleman 
torch.Size([2, 3]) → 2D, 2 satır × 3 sütun
torch.Size([2, 3, 4]) → 3D

In [4]:
X = torch.tensor([
    [25, 50000, 650],
    [40, 80000, 720]
], dtype=torch.float32)
X.shape

torch.Size([2, 3])

In [5]:
from torch.utils.data import TensorDataset

In [6]:
y = torch.tensor([0, 1])

In [7]:
dataset = TensorDataset(X, y)

In [8]:
len(dataset)

2

In [9]:
dataset[0]

(tensor([2.5000e+01, 5.0000e+04, 6.5000e+02]), tensor(0))

In [11]:
from torch.utils.data import DataLoader
loader = DataLoader(dataset, batch_size=1)

In [12]:
for X_batch, y_batch in loader:
    print(X_batch)
    print(y_batch)

tensor([[2.5000e+01, 5.0000e+04, 6.5000e+02]])
tensor([0])
tensor([[4.0000e+01, 8.0000e+04, 7.2000e+02]])
tensor([1])


\[
z = xW^T + b
\]

In [14]:
import torch.nn as nn

In [17]:
layer = nn.Linear(3, 2)
output = layer(X)
output

tensor([[ -6604.2959,  17399.5625],
        [-10580.7383,  27759.3945]], grad_fn=<AddmmBackward0>)

In [18]:
layer.weight

Parameter containing:
tensor([[-0.3625, -0.1325,  0.0442],
        [-0.4111,  0.3449,  0.2506]], requires_grad=True)

In [19]:
layer.bias

Parameter containing:
tensor([-0.4814, -0.4968], requires_grad=True)

In [20]:
relu = nn.ReLU()

In [21]:
relu_output = relu(output)
relu_output

tensor([[    0.0000, 17399.5625],
        [    0.0000, 27759.3945]], grad_fn=<ReluBackward0>)