In [31]:
import torch
x = torch.tensor([1, 2, 3])
print(x)
print(x.dtype)

tensor([1, 2, 3])
torch.int64


In [32]:
x_float = torch.tensor([1, 2, 3], dtype=torch.float32)
print(x_float)
print(x_float.dtype)

tensor([1., 2., 3.])
torch.float32


In [33]:
x_float.shape

torch.Size([3])

torch.Size([3]) → 1D, 3 eleman 
torch.Size([2, 3]) → 2D, 2 satır × 3 sütun
torch.Size([2, 3, 4]) → 3D

In [34]:
X = torch.tensor([
    [25, 50000, 650],
    [40, 80000, 720]
], dtype=torch.float32)
X.shape

torch.Size([2, 3])

In [35]:
from torch.utils.data import TensorDataset

In [36]:
y = torch.tensor([0, 1])

In [37]:
dataset = TensorDataset(X, y)

In [38]:
len(dataset)

2

In [39]:
dataset[0]

(tensor([2.5000e+01, 5.0000e+04, 6.5000e+02]), tensor(0))

In [40]:
from torch.utils.data import DataLoader
loader = DataLoader(dataset, batch_size=1)

In [41]:
for X_batch, y_batch in loader:
    print(X_batch)
    print(y_batch)

tensor([[2.5000e+01, 5.0000e+04, 6.5000e+02]])
tensor([0])
tensor([[4.0000e+01, 8.0000e+04, 7.2000e+02]])
tensor([1])


\[
z = xW^T + b
\]

In [42]:
import torch.nn as nn

In [43]:
layer = nn.Linear(3, 2)
output = layer(X)
output

tensor([[-12084.4707,  20633.5508],
        [-19438.4258,  33135.1250]], grad_fn=<AddmmBackward0>)

In [44]:
layer.weight

Parameter containing:
tensor([[-0.4540, -0.2457,  0.3231],
        [ 0.5400,  0.4173, -0.3796]], requires_grad=True)

In [45]:
layer.bias

Parameter containing:
tensor([-0.1952,  0.0475], requires_grad=True)

In [46]:
relu = nn.ReLU()

In [47]:
relu_output = relu(output)
relu_output

tensor([[    0.0000, 20633.5508],
        [    0.0000, 33135.1250]], grad_fn=<ReluBackward0>)

In [67]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Linear(3, 2)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(2, 1)

    def forward(self, x):
         x = self.layer1(x)
         x = self.relu(x)
         x = self.layer2(x)
         return x

model = NeuralNetwork()
output = model(X)
output  


tensor([[-189.3483],
        [-297.7169]], grad_fn=<AddmmBackward0>)

In [49]:
print(output.shape)
y = y.reshape(-1, 1)
print(y.shape)

torch.Size([2, 1])
torch.Size([2, 1])


In [68]:
loss_fn = nn.MSELoss()
loss = loss_fn(output, y)
loss

tensor(62542.2812, grad_fn=<MseLossBackward0>)

In [65]:

print(y.dtype)
print(output.dtype)

torch.float32
torch.float32


In [59]:
y=y.float()

In [69]:
loss.backward()
print(model.layer1.weight.grad)

tensor([[6.7196e+02, 1.3439e+06, 1.3621e+04],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [70]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [71]:
optimizer.step()

In [72]:
optimizer.zero_grad()

In [78]:
model = NeuralNetwork()

In [79]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [80]:
print(model.layer1.weight)

Parameter containing:
tensor([[ 0.0190,  0.0638, -0.0659],
        [-0.2279,  0.2634, -0.3451]], requires_grad=True)


In [81]:
optimizer.zero_grad()

output = model(X)
loss = loss_fn(output, y)

loss.backward()
optimizer.step()

In [82]:
print(model.layer1.weight)

Parameter containing:
tensor([[-2.7945e+03, -5.5890e+06, -5.6557e+04],
        [-5.2699e+03, -1.0539e+07, -1.0665e+05]], requires_grad=True)


### Feature scaling sadece klasik ML'de değil, neural network eğitiminde de önemlidir.
X.mean(dim=0) → her feature'ın ortalaması , 
X.std(dim=0) → her feature'ın standart sapması , 
sonuç → feature'ların ölçekleri birbirine yaklaştırılmış olur.

In [83]:
X_scaled = (X - X.mean(dim=0)) / X.std(dim=0)
X_scaled

tensor([[-0.7071, -0.7071, -0.7071],
        [ 0.7071,  0.7071,  0.7071]])

In [84]:
model = NeuralNetwork()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):
    optimizer.zero_grad()
    output = model(X_scaled)
    loss = loss_fn(output, y)
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(epoch, loss.item())

0 0.2616220712661743
10 0.18053439259529114
20 0.13560210168361664
30 0.10836668312549591
40 0.09026377648115158
50 0.0771268829703331
60 0.0668693408370018
70 0.058422546833753586
80 0.05122501403093338
90 0.04496969282627106


In [86]:
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=2)
for X_batch, y_batch in loader:
    print(X_batch)
    print(y_batch)

tensor([[2.5000e+01, 5.0000e+04, 6.5000e+02],
        [4.0000e+01, 8.0000e+04, 7.2000e+02]])
tensor([[0.],
        [1.]])
